kyverno:
  plugin:
    enabled: true

sourceFilters:
  - selector:
      # -- select Report by source
      source: kyverno
    # -- Filter out Reports of controlled Pods and Jobs, only works for Reports with scope resource
    uncontrolledOnly: false

ui:
  enabled: true
  customBoards:
    - name: "Project 12345 Dashboard"
      namespaces:
        selector:
          projectId: pid12345
      sources:
        list:
          - kyverno
      clusterScope:
        enabled: false

# helm install policy-reporter policy-reporter/policy-reporter -f reporter-values.yaml --create-namespace -n policy-reporter --version=3.4.2
