apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-image-tag
  annotations:
    policies.kyverno.io/title: Validate Image Tag
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod 
    #pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      The ':latest' tag is mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that maps to
      a specific version of an application Pod.     
spec:
  background: true
  rules:
  - name: deny-latest-tag
    context:
      - name: namespacefilters
        configMap:
          name: namespace-filters
          namespace: kyverno
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{request.object.metadata.namespace}}" 
        operator: AnyNotIn
        value: "{{namespacefilters.data.exclude}}"
    validate:
      failureAction: Audit
      message: "Using the mutable image tag 'latest' is not allowed."
      pattern:
        spec:
          =(containers):
          - image: "!*:latest"
